<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'elFinder'                      => __DIR__ . '/src/QuElFinder/php/elFinder.class.php',
    'elFinderConnector'             => __DIR__ . '/src/QuElFinder/php/elFinderConnector.class.php',
    'elFinderVolumeDriver'          => __DIR__ . '/src/QuElFinder/php/elFinderVolumeDriver.class.php',
    'elFinderVolumeLocalFileSystem' => __DIR__ . '/src/QuElFinder/php/elFinderVolumeLocalFileSystem.class.php',
    'elFinderVolumeMySQL'           => __DIR__ . '/src/QuElFinder/php/elFinderVolumeMySQL.class.php',
);