<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Qu ElFinder');
    echo $this->headLink()
        ->prependStylesheet($this->basePath($QuBasePath) . '/css/style.css')
        ->prependStylesheet($this->basePath($QuBasePath) . '/css/theme.css')
        ->prependStylesheet($this->basePath($QuBasePath) . '/css/elfinder.min.css')
        ->prependStylesheet($this->basePath($QuBasePath) . '/jquery/ui-themes/smoothness/jquery-ui-1.10.1.custom.css');
    echo $this->headScript()
        ->prependFile($this->basePath($QuBasePath) . '/jquery/jquery-ui-1.8.23.custom.min.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/jquery/jquery-1.9.1.min.js', 'text/javascript');
    ?>
</head>
<body>
<div id="elfinder"></div>
<script type="text/javascript" charset="utf-8">

    // The info provider https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor
    // Helper function to get parameters from the query string.
    function getUrlParam(paramName) {
        var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i') ;
        var match   = window.location.search.match(reParam) ;
        return (match && match.length > 1) ? match[1] : '' ;
    }
    var funcNum = getUrlParam('CKEditorFuncNum');

</script>
<?php
    echo
    $this->QuElFinder(
       'elfinder',
        array(
            'width' => "100%",
            'height' => "582",
            'resizable' => false,
            'getFileCallback' => new Zend\Json\Expr('function(file){
            window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
            window.close();
             }'),
        )
    );
    echo $this->inlineScript()
?>
</body>
</html>