

<?php  $this->headTitle('Qu ElFinder'); ?>


<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <h1>
                Qu <a href="http://elfinder.org/">
                    ElFinder
                    <small>visit website</small>
                </a>
            </h1>
            <div id="elfinder"></div>
        </div>
    </div>
</div>

<?php
    echo
    $this->QuElFinder(
        'elfinder',
        array(
            'width' => "100%",
            'height' => "600",
        )
    );
?>








<!-- DISQUS -->
<div class="container">
    <div class="row">
        <div class="span12">
            <br><br>
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                var disqus_shortname = 'qumodules';
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
        </div>
    </div>
</div>
