<?
    /**
     * Author: Cel Ticó Petit
     *
     * Company: Cencis s.c.p.
     * Contact: cel@cenics.net
     */
    $this->headTitle('Qu ElFinder');
    $this->headLink()
        ->prependStylesheet($this->basePath($QuBasePath) . '/css/theme.css')
        ->prependStylesheet($this->basePath($QuBasePath) . '/css/elfinder.min.css')
        ->prependStylesheet($this->basePath($QuBasePath) . '/jquery/ui-themes/smoothness/jquery-ui-1.8.23.custom.css')
    ;
    $this->headScript()
        ->prependFile($this->basePath($QuBasePath) . '/js/i18n/elfinder.ca.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/js/elfinder.min.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/jquery/jquery-ui-1.8.23.custom.min.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/jquery/jquery-1.8.1.min.js', 'text/javascript')

    ;
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div id="elfinder"></div>
        </div>
    </div>
</div>
<script type="text/javascript">

    $('#elfinder').elfinder({
        url : '<?=$ConnectorPath?>',
        height:'500'
    }).elfinder('instance');

</script>


